import type { BlockSchema } from '#shared/types/cms'

export default {
	type: 'TechStack',
	label: 'Tech Stack',
	group: 'Content',
	fields: [
		{ name: 'eyebrow', label: 'Eyebrow', type: 'text', default: '' },
		{ name: 'heading', label: 'Heading', type: 'text', default: '' },
		{ name: 'sub', label: 'Subheading', type: 'text', default: '' },
		{
			name: 'items',
			label: 'Tools',
			type: 'repeater',
			default: [],
			fields: [
				{
					name: 'icon',
					label: 'Icon',
					type: 'select',
					default: 'simple-icons:javascript',
					options: [
						{ label: '.NET', value: 'simple-icons:dotnet' },
						{ label: 'Alpine.js', value: 'simple-icons:alpinedotjs' },
						{ label: 'Android Studio', value: 'simple-icons:androidstudio' },
						{ label: 'Angular', value: 'simple-icons:angular' },
						{ label: 'Ansible', value: 'simple-icons:ansible' },
						{ label: 'Astro', value: 'simple-icons:astro' },
						{ label: 'AWS', value: 'simple-icons:amazonwebservices' },
						{ label: 'Azure', value: 'simple-icons:microsoftazure' },
						{ label: 'Bootstrap', value: 'simple-icons:bootstrap' },
						{ label: 'Bulma', value: 'simple-icons:bulma' },
						{ label: 'C', value: 'simple-icons:c' },
						{ label: 'C#', value: 'simple-icons:csharp' },
						{ label: 'C++', value: 'simple-icons:cplusplus' },
						{ label: 'Clojure', value: 'simple-icons:clojure' },
						{ label: 'Cloudflare', value: 'simple-icons:cloudflare' },
						{ label: 'Contentful', value: 'simple-icons:contentful' },
						{ label: 'CSS3', value: 'simple-icons:css3' },
						{ label: 'Cypress', value: 'simple-icons:cypress' },
						{ label: 'Dart', value: 'simple-icons:dart' },
						{ label: 'DigitalOcean', value: 'simple-icons:digitalocean' },
						{ label: 'Django', value: 'simple-icons:django' },
						{ label: 'Docker', value: 'simple-icons:docker' },
						{ label: 'Elasticsearch', value: 'simple-icons:elasticsearch' },
						{ label: 'Elixir', value: 'simple-icons:elixir' },
						{ label: 'Ember.js', value: 'simple-icons:emberdotjs' },
						{ label: 'ESLint', value: 'simple-icons:eslint' },
						{ label: 'Express', value: 'simple-icons:express' },
						{ label: 'FastAPI', value: 'simple-icons:fastapi' },
						{ label: 'Figma', value: 'simple-icons:figma' },
						{ label: 'Firebase', value: 'simple-icons:firebase' },
						{ label: 'Flask', value: 'simple-icons:flask' },
						{ label: 'Flutter', value: 'simple-icons:flutter' },
						{ label: 'Gatsby', value: 'simple-icons:gatsby' },
						{ label: 'Git', value: 'simple-icons:git' },
						{ label: 'GitHub', value: 'simple-icons:github' },
						{ label: 'GitHub Actions', value: 'simple-icons:githubactions' },
						{ label: 'GitLab', value: 'simple-icons:gitlab' },
						{ label: 'Go', value: 'simple-icons:go' },
						{ label: 'Google Cloud', value: 'simple-icons:googlecloud' },
						{ label: 'GraphQL', value: 'simple-icons:graphql' },
						{ label: 'Haskell', value: 'simple-icons:haskell' },
						{ label: 'Heroku', value: 'simple-icons:heroku' },
						{ label: 'HTML5', value: 'simple-icons:html5' },
						{ label: 'Java', value: 'simple-icons:openjdk' },
						{ label: 'JavaScript', value: 'simple-icons:javascript' },
						{ label: 'Jest', value: 'simple-icons:jest' },
						{ label: 'Jira', value: 'simple-icons:jira' },
						{ label: 'jQuery', value: 'simple-icons:jquery' },
						{ label: 'Kotlin', value: 'simple-icons:kotlin' },
						{ label: 'Kubernetes', value: 'simple-icons:kubernetes' },
						{ label: 'Laravel', value: 'simple-icons:laravel' },
						{ label: 'Lua', value: 'simple-icons:lua' },
						{ label: 'Magento', value: 'simple-icons:magento' },
						{ label: 'MariaDB', value: 'simple-icons:mariadb' },
						{ label: 'MongoDB', value: 'simple-icons:mongodb' },
						{ label: 'MySQL', value: 'simple-icons:mysql' },
						{ label: 'NestJS', value: 'simple-icons:nestjs' },
						{ label: 'Netlify', value: 'simple-icons:netlify' },
						{ label: 'Next.js', value: 'simple-icons:nextdotjs' },
						{ label: 'Nginx', value: 'simple-icons:nginx' },
						{ label: 'Node.js', value: 'simple-icons:nodedotjs' },
						{ label: 'Notion', value: 'simple-icons:notion' },
						{ label: 'npm', value: 'simple-icons:npm' },
						{ label: 'Nuxt', value: 'simple-icons:nuxt' },
						{ label: 'Perl', value: 'simple-icons:perl' },
						{ label: 'PHP', value: 'simple-icons:php' },
						{ label: 'Playwright', value: 'simple-icons:playwright' },
						{ label: 'pnpm', value: 'simple-icons:pnpm' },
						{ label: 'PostgreSQL', value: 'simple-icons:postgresql' },
						{ label: 'Postman', value: 'simple-icons:postman' },
						{ label: 'Prettier', value: 'simple-icons:prettier' },
						{ label: 'Prisma', value: 'simple-icons:prisma' },
						{ label: 'Python', value: 'simple-icons:python' },
						{ label: 'R', value: 'simple-icons:r' },
						{ label: 'React', value: 'simple-icons:react' },
						{ label: 'Redis', value: 'simple-icons:redis' },
						{ label: 'Remix', value: 'simple-icons:remix' },
						{ label: 'Ruby', value: 'simple-icons:ruby' },
						{ label: 'Ruby on Rails', value: 'simple-icons:rubyonrails' },
						{ label: 'Rust', value: 'simple-icons:rust' },
						{ label: 'Sanity', value: 'simple-icons:sanity' },
						{ label: 'Sass', value: 'simple-icons:sass' },
						{ label: 'Scala', value: 'simple-icons:scala' },
						{ label: 'Shopify', value: 'simple-icons:shopify' },
						{ label: 'Slack', value: 'simple-icons:slack' },
						{ label: 'Solid', value: 'simple-icons:solid' },
						{ label: 'Spring', value: 'simple-icons:spring' },
						{ label: 'SQLite', value: 'simple-icons:sqlite' },
						{ label: 'Storybook', value: 'simple-icons:storybook' },
						{ label: 'Strapi', value: 'simple-icons:strapi' },
						{ label: 'Styled Components', value: 'simple-icons:styledcomponents' },
						{ label: 'Supabase', value: 'simple-icons:supabase' },
						{ label: 'Svelte', value: 'simple-icons:svelte' },
						{ label: 'Swift', value: 'simple-icons:swift' },
						{ label: 'Tailwind CSS', value: 'simple-icons:tailwindcss' },
						{ label: 'Terraform', value: 'simple-icons:terraform' },
						{ label: 'Testing Library', value: 'simple-icons:testinglibrary' },
						{ label: 'TypeScript', value: 'simple-icons:typescript' },
						{ label: 'Vercel', value: 'simple-icons:vercel' },
						{ label: 'Vite', value: 'simple-icons:vite' },
						{ label: 'Vitest', value: 'simple-icons:vitest' },
						{ label: 'VS Code', value: 'simple-icons:visualstudiocode' },
						{ label: 'Vue.js', value: 'simple-icons:vuedotjs' },
						{ label: 'Webflow', value: 'simple-icons:webflow' },
						{ label: 'Webpack', value: 'simple-icons:webpack' },
						{ label: 'WooCommerce', value: 'simple-icons:woocommerce' },
						{ label: 'WordPress', value: 'simple-icons:wordpress' },
						{ label: 'Xcode', value: 'simple-icons:xcode' },
						{ label: 'Yarn', value: 'simple-icons:yarn' },
					],
				},
				{ name: 'name', label: 'Name (e.g. Vue.js)', type: 'text', default: '' },
			],
		},
	],
} satisfies BlockSchema
